# Generated by Django 3.1 on 2020-08-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DJI30',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
