# Generated by Django 3.1 on 2020-08-27 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fintech', '0002_auto_20200827_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Symbol')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('adj_close', models.FloatField(verbose_name='Adj. close')),
                ('volume', models.FloatField(verbose_name='Volume')),
            ],
        ),
        migrations.CreateModel(
            name='DJI30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fintech.stock')),
            ],
        ),
    ]
